### ISSUE TITLE
PhotoPrism - Admin user

### ISSUE THREAD

**Issue by jlw4049** [ich777/docker-templates#18]
Would it be possible for you to update the container to support 

PHOTOPRISM_ADMIN_USER

so we can use something other than admin?

**Comment by ich777** [comment]
I'm not to sure since this seems like a pretty dramatic change to the template.
If you really want to define a another user as the admin user wouldn't it be better to add it manually to the template?
When this variable is added, this would ultimately mean I also have to make the variable required and/or already fill it out with `admin` to not confuse users too much.

Does PhotoPrism support multiple users now?

**Comment by jlw4049** [comment]
They do not support multiple users now. However, we can easily use multiple instances, which is plenty good enough for me.

I attempted to pass the run command and the env variable and both causes your image not to work. I would have otherwise just added it to the template, not sure why but I tried several times.

**Comment by ich777** [comment]
I just made the template and it‘s the official container, correct.

If it is not working I would recommend that you go to the PhotoPrism GitHub and report it there.
There should be no reason why it shouldn‘t work when you‘ve added the variable to the template.

**Comment by jlw4049** [comment]
My bad, I should have looked closer before reporting an issue. Template works great btw!
