### ISSUE TITLE
Assetto Corsa Docker Image Unable to change race settings

### ISSUE THREAD

**Issue by tscanlon** [ich777/docker-templates#19]
I was playing around with the container and was able to get a server up and running and connect to it. I was wondering if there was some undocumented flag to pass it a different server configuration that you can output from Content Manager. As far as I can tell its only setup to be able to do one race (one type of car, on one track, with only one set of configurations around the duration of the race).

Still new to configuring AC servers but seems like you'd want to hand it a path to a tarball that has the configuration bundle from content manager, extract that and run `./acServer` but I'm really far out of the loop on how docker and the steam stuff works.

Thanks for your time, I've been using the valhiem image and its been working nicely.

**Comment by ich777** [comment]
May I ask on what platform do you use my container? If Unraid then please use the support forums or if really needed the GitHub Issue tracker over [here](https://github.com/ich777/docker-steamcmd-server/tree/assettocorsa). This is the wrong repository to report that because these are only the templates.

As far as I know you just insert the configuration and that's it, at least that's what I remember I had to do to change the settings when testing it back then. I'm really sorry but I haven't done anything related to AssettoCorsa in a long time and it would be better suited in the Unraid support forums as long as you are using Unraid.

**Comment by tscanlon** [comment]
Thanks, I think the dockerfile will give me a few threads to pull on and I will use the forum after as it is the platform I'm using. Sorry for the noise and thank you for the redirects.
